### ISSUE TITLE
Explore Page

### ISSUE THREAD

**Issue by artofnuel** [zuri-training/COL_FILMS_TEAM_114#14]
The page that houses videos.

**Comment by Mimiugeh** [comment]
Approved and handed to devs✅

**Comment by artofnuel** [comment]
https://www.figma.com/proto/PAhnmLoO7tZTieCo4zc8Nl/Approved-designs-for-team-114?node-id=861%3A2273&scaling=min-zoom&page-id=0%3A1

**Comment by Mimiugeh** [comment]
Link to mobile view- https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1265%3A10185&scaling=scale-down&page-id=1265%3A8249&starting-point-node-id=1336%3A8897 

Link to desktop view- https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A12847&scaling=scale-down&page-id=66%3A109&starting-point-node-id=1156%3A10155
