### ISSUE TITLE
Reset Password Page

### ISSUE THREAD

**Issue by artofnuel** [zuri-training/COL_FILMS_TEAM_114#21]
You are to create a Reset Password Page Using the [Designs](https://www.figma.com/file/PAhnmLoO7tZTieCo4zc8Nl/Approved-designs-for-team-114?node-id=2%3A434) from the Designers team. Push your code to the alpha branch.

**Comment by tarakuds** [comment]
Ok. Getting to work

**Comment by tarakuds** [comment]
Here is a link to a live editor. Work in progress

https://codepen.io/TeeA/pen/eYMrPdN
