### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by artofnuel** [zuri-training/COL_FILMS_TEAM_114#22]
You are to create a Settings Page Using the [Designs](https://www.figma.com/file/PAhnmLoO7tZTieCo4zc8Nl/Approved-designs-for-team-114?node-id=2%3A434) from the Designers team. Push your code to the alpha branch.

**Comment by oliviachidi** [comment]
https://github.com/zuri-training/COL_FILMS_TEAM_114/blob/alpha/settings-upload/settings.html
