### ISSUE TITLE
Help Center Creators and FAQ Page

### ISSUE THREAD

**Issue by artofnuel** [zuri-training/COL_FILMS_TEAM_114#28]
You are to create aHelp Center Creators and FAQ Page Using the [Designs](https://www.figma.com/file/PAhnmLoO7tZTieCo4zc8Nl/Approved-designs-for-team-114?node-id=2%3A434) from the Designers team. Push your code to the alpha branch.

Remember to make your code responsive to mobile view of max-width 400px.

**Comment by thetamaraelaye** [comment]
The accordion is not optimal but it works. This was challenging. Thanks.

Here is a link to a live server: https://help-centre.tamaraelaye.repl.co/helpcentre.html
