### ISSUE TITLE
Forget password page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#34]

**Comment by Oluwasanjo21** [comment]
Mobile version:
https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1265%3A8416&scaling=scale-down&page-id=1265%3A8249&starting-point-node-id=1336%3A8897

**Comment by Oluwasanjo21** [comment]
Desktop version:
https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A8753&scaling=min-zoom&page-id=66%3A109&starting-point-node-id=1156%3A10155
