### ISSUE TITLE
Page not found 

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#35]

**Comment by Oluwasanjo21** [comment]
Mobile version:
https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1265%3A8250&scaling=scale-down&page-id=1265%3A8249&starting-point-node-id=1336%3A8897

**Comment by Oluwasanjo21** [comment]
Desktop Version:
https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A9100&scaling=min-zoom&page-id=66%3A109&starting-point-node-id=1156%3A10155
