### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#36]

**Comment by Oluwakoya-ao** [comment]
This is the design link to the hifi of the edit Profile page
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A11484

This is the design link to the hifi of the edit profile page (Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1268%3A8462

This is the design link to the lofi of the edit profile page
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1216%3A8896

This is the design link to the lofi of the edit profile page ( Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A12487

This is the design link to the wireframe of the edit profile page
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A11316

This is the design link to the wireframe of the edit profile ( Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A8979
