### ISSUE TITLE
Change password page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#37]

**Comment by Oluwakoya-ao** [comment]
This is the design link to the hifi for the Change Password page
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A11519

This is the design link to the hifi for the change password (Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1268%3A8766

This is the design link to the lofi for the change password page.
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1172%3A9030

This is the design link to the lofi for the change password (Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A12397

This is the design link to the wireframe for the change password
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A11272

This is the design link to the wireframe for the reset password (Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A8942
