### ISSUE TITLE
Design the Settings page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#38]

**Comment by Oluwakoya-ao** [comment]
This is the design link to the hifi for settings page (Account page)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A10167

The  mobile responsive view is different from the desktop view so there are two links 
This is the design link to the hifi for settings page (Mobile Responsive view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1268%3A8678
This is the design  link to the hifi for the account page (Mobile responsive view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1268%3A8618

This is the design link to the lofi for settings page (Account page)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1172%3A8615

This is the design  link to the lofi for settings page (responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A12443
This is the design  link to the lofi for account page (responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A12332

This is the design link to the wireframe for settings page (Account page)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A11220

This is the design link to the wireframe for settings page (Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A8722
This is the design link to the wieframe for the Account page (Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A8774
