### ISSUE TITLE
Design the Error 504 - Gateway timeout 

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#39]

**Comment by fade-xo** [comment]
Error 504 Page web view here: https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?page-id=66%3A109&node-id=1129%3A9353&viewport=2958%2C2383%2C0.2&scaling=min-zoom&starting-point-node-id=1156%3A10155

Error 504 Page mobile view here: https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?page-id=66%3A109&node-id=1129%3A9682&viewport=-526%2C1211%2C0.07&scaling=min-zoom&starting-point-node-id=1156%3A10155
