### ISSUE TITLE
Searched videos page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#41]

**Comment by Oluwasanjo21** [comment]
Link to Desktop Design:
https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A11557&scaling=scale-down&page-id=66%3A109&starting-point-node-id=1156%3A10155

**Comment by Oluwasanjo21** [comment]
Mobile design:
https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1265%3A9735&scaling=scale-down&page-id=1265%3A8249&starting-point-node-id=1265%3A11304
