### ISSUE TITLE
Design the Help page & faq page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#43]

**Comment by Oludotunkt** [comment]
Prototype of the Mobile version of Help center/FAQ:
https://www.figma.com/proto/wQwipF2g2W8LTOiKrg68wo/Wireframe-for-the-Varsity-Vines-mobile-version?page-id=0%3A1&node-id=49%3A1768&viewport=-1297%2C-1306%2C0.26&scaling=scale-down&starting-point-node-id=34%3A765&show-proto-sidebar=1

**Comment by Oludotunkt** [comment]
Prototype of the desktop version:

https://www.figma.com/proto/wQwipF2g2W8LTOiKrg68wo/Wireframe-for-the-Varsity-Vines-mobile-version?page-id=0%3A1&node-id=68%3A2711&viewport=-2634%2C-2188%2C0.28&scaling=scale-down&starting-point-node-id=32%3A727&show-proto-sidebar=1
