### ISSUE TITLE
Design the Notification page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#45]

**Comment by Mimiugeh** [comment]
Reviewed and passed to devs

**Comment by Mimiugeh** [comment]
Link to the desktop view- https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A13133&scaling=scale-down&page-id=66%3A109&starting-point-node-id=1156%3A10155

link to the mobile view- https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1265%3A10336&scaling=scale-down&page-id=1265%3A8249&starting-point-node-id=1336%3A8897)
