### ISSUE TITLE
Design the Content creator page/home

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#46]

**Comment by Agboehi** [comment]
Designed the content creator page - home - mobile  responsiveness
 https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1265%3A11089

**Comment by Agboehi** [comment]
Designed the content creator page - home - desktop responsiveness
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1144%3A8435
