### ISSUE TITLE
Sign In Page

### ISSUE THREAD

**Issue by artofnuel** [zuri-training/COL_FILMS_TEAM_114#5]
You are to create a sign in page Using the [Designs](https://www.figma.com/file/PAhnmLoO7tZTieCo4zc8Nl/Approved-designs-for-team-114?node-id=2%3A434) from the Designers team. Push your code to the alpha branch.

Remember to make your code responsive to mobile view of max-width 400px

**Comment by techbee001** [comment]
The designs have been done and I'm currently working on these Improvements:
- the small text that I found difficult to read on a mobile device.

- The input boxes and buttons have a small height. Or I can leave it if it’s not a problem . 

- Between screen width 641 and about 400, the left side of the form got cut off.

- Some of the images look squashed. So I will have to work on image responsiveness as well
