### ISSUE TITLE
Design the Library (Watch later, history and playlist)	

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#51]
Done

**Comment by Vivy2** [comment]
Done

**Comment by Vivy2** [comment]
Desktop view
https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1196%3A10690&scaling=min-zoom&page-id=1196%3A8156&starting-point-node-id=1196%3A11697

**Comment by Vivy2** [comment]
Mobile view

https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1265%3A10537&scaling=min-zoom&page-id=1265%3A8249&starting-point-node-id=1265%3A9272&show-proto-sidebar=1

**Comment by Vivy2** [comment]
Mobile view

https://www.figma.com/proto/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1265%3A10537&scaling=min-zoom&page-id=1265%3A8249&starting-point-node-id=1265%3A9272&show-proto-sidebar=1
