### ISSUE TITLE
Design the Notifcation settings page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#71]

**Comment by Oluwakoya-ao** [comment]
This is the design link to the hifi for notification settings page 
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A12597

This is the design link to the lofi for the notification settings page
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1216%3A8355

This is the design link to the hifi for notification settings page (reponsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1268%3A8509
 
This is the design link to the lofi for notification settings page (responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3

This is the design  link to the wireframe for notification settings page 
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A11397

This is the design link to the wireframe for notification settings page (responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A10125
