### ISSUE TITLE
Design the privacy settings page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#72]

**Comment by Oluwakoya-ao** [comment]
This is the design link to the hifi for the privacy page
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1129%3A12566

This is the design link to the hifi for the privacy page ( Mobile responsive view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1268%3A8811

This is the design link to the lofi for the privacy page
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1172%3A8668

This is the design link to the lofi for the privacy page ( Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A12613

This is the design link to the wireframe for the privacy page
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A11360

This is the design link to the wireframe for the privacy page (Responsive mobile view)
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1092%3A8742
