### ISSUE TITLE
Design the settings side bar

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#94]

**Comment by Oluwakoya-ao** [comment]
This is the design link to the hifi for the settings side bar
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1452%3A13689

This is the design  link to the lofi for the settings side bar
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1452%3A13660

This is the design link to the wireframe for the settings side bar
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1452%3A13653
