### ISSUE TITLE
Design the privacy policy page

### ISSUE THREAD

**Issue by zezerocks** [zuri-training/COL_FILMS_TEAM_114#98]
Design the privacy policy page of varsity vines

**Comment by Dampekmedia** [comment]
**Here is the  link to the privacy policy page of varsity vines (Desktop View)**
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1508%3A8282
**Here is the  link to the privacy policy page of varsity vines (Mobile View)**
https://www.figma.com/file/ptHO9jzg1PZU8eRwm3MciQ/UI-FILE?node-id=1513%3A8305
